Fix 'AttributeError: 'FieldInfo' object has no attribute 'disable_on_mongo'. (#21)
This would occur when field was declared without `Field()` function