Hotfix/many to many updates (#22)
* WIP: Fix many-to-many relationships updates

* WIP: Clean up the SQL CRUD methods

* WIP: Enable nested updates in SQL

* WIP: Clean up the SQL update method

* Fix 'AttributeError: 'int' object has no attribute 'id'' with SQL update

* Fix failing tests

* Fix dependency errors in python 3.13

* Fix failing CI tests for examples

* Fix 'TypeError: field 'TodoList.description' was not initialized with a Field() or Relationship()'

* Add tests for blog example in github CI